version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
  scraper:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "./entrypoint.sh ${DJANGO_SUPERUSER_USERNAME} ${DJANGO_SUPERUSER_PASSWORD} ${DJANGO_SUPERUSER_EMAIL}"
    depends_on:
      - db
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    command: sh -c "celery -A celerytask.celery worker -l info"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
      - scraper 
  celery-beat:
    restart: always
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    command: sh -c "celery -A celerytask.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
      - scraper 
volumes:
  pgdata: